env:
  global:
    - CC_TEST_REPORTER_ID=$CC_REPORTER_ID
language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
language: node_js
node_js:
  - "8"
script:
  - npm run lintjs
  - npm run build 
notifications:
  webhooks:
    urls: https://api.netlify.com/build_hooks/$NETLIFY_HOOK_ID
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
# safelist
branches:
  only:
  - master
  - development
