backend:
  name: github 
  repo: rodgerpaulo/rogerramos.me

media_folder: static/assets
public_folder: assets

display_url: https://rogerramos.me

collections:
  - name: Log Entries
    label: LogEntries
    folder: entries
    create: true
    fields:
      - { name: custom_url, label: Custom url, required: false }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: hero, label: Hero, widget: image, required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["javascript"] }
      - { name: body, label: Body, widget: markdown }
